import { useState } from "react";
import axios from "axios";
import { motion } from "framer-motion";
import jsPDF from "jspdf";

const API = import.meta.env.VITE_API_URL || "http://localhost:5000";

function Home() {
  const [url, setUrl] = useState("");
  const [review, setReview] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async () => {
    if (!url) return alert("Enter URL");

    setLoading(true);
    setReview(null);

    try {
      const { data } = await axios.post(`${API}/api/reviews`, { url });
      setReview(data);
    } catch (err) {
      alert(err.response?.data?.message || "Something went wrong");
    } finally {
      setLoading(false);
    }
  };

  const grouped =
    review?.issues?.reduce((acc, issue) => {
      acc[issue.category] = acc[issue.category] || [];
      acc[issue.category].push(issue);
      return acc;
    }, {}) || {};

  const exportPDF = () => {
    const pdf = new jsPDF();
    let y = 20;

    const date = new Date().toLocaleString();

    // COVER PAGE
    pdf.setFontSize(22);
    pdf.text("AI UX Audit Report", 105, 40, { align: "center" });

    pdf.setFontSize(14);
    pdf.text(`Website: ${url}`, 105, 55, { align: "center" });
    pdf.text(`Generated On: ${date}`, 105, 65, { align: "center" });

    pdf.setFontSize(40);
    pdf.text(`${review.score}`, 105, 95, { align: "center" });

    pdf.setFontSize(14);
    pdf.text("Overall UX Score", 105, 110, { align: "center" });

    pdf.addPage();
    y = 20;

    // ISSUES SECTION
    pdf.setFontSize(18);
    pdf.text("UX Issues Analysis", 14, y);
    y += 10;

    Object.keys(grouped).forEach((category) => {
      pdf.setFontSize(14);
      pdf.text(category.toUpperCase(), 14, y);
      y += 8;

      grouped[category].forEach((issue) => {
        pdf.setFontSize(12);
        pdf.text(`• ${issue.title}`, 16, y);
        y += 6;

        pdf.setFontSize(10);
        pdf.text(pdf.splitTextToSize(issue.reason, 170), 18, y);
        y += 8;

        pdf.text(pdf.splitTextToSize("Proof: " + issue.proof, 170), 18, y);
        y += 10;

        if (y > 270) {
          pdf.addPage();
          y = 20;
        }
      });

      y += 5;
    });

    pdf.addPage();
    y = 20;

    // IMPROVEMENTS SECTION
    pdf.setFontSize(18);
    pdf.text("Top Improvement Suggestions", 14, y);
    y += 10;

    review.suggestions.forEach((s, index) => {
      pdf.setFontSize(12);
      pdf.text(`Improvement ${index + 1}`, 14, y);
      y += 6;

      pdf.setFontSize(10);
      pdf.text(pdf.splitTextToSize("Before: " + s.before, 170), 16, y);
      y += 8;

      pdf.text(pdf.splitTextToSize("After: " + s.after, 170), 16, y);
      y += 12;

      if (y > 270) {
        pdf.addPage();
        y = 20;
      }
    });

    // FOOTER ON ALL PAGES
    const pageCount = pdf.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.text(
        `Generated by AI UX Reviewer | Page ${i} of ${pageCount}`,
        105,
        290,
        { align: "center" },
      );
    }

    pdf.save("ux-report.pdf");
  };

  return (
    <div className="min-h-screen bg-slate-950 text-white p-8">
      <motion.h1
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="text-4xl text-center font-bold mb-12"
      >
        Website UX Reviewer
      </motion.h1>

      {/* Input Section */}
      <div className="bg-slate-900 p-6 rounded-2xl border border-white/10 shadow-lg">
        <div className="flex gap-4">
          <input
            className="flex-1 p-4 bg-slate-800 border border-white/10 rounded-xl focus:ring-2 focus:ring-indigo-500 outline-none"
            placeholder="Enter website URL"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
          />
          <button
            onClick={handleSubmit}
            className="px-6 bg-indigo-600 hover:bg-indigo-700 rounded-xl transition cursor-pointer"
          >
            Analyze
          </button>
        </div>
      </div>

      {loading && (
        <div className="flex justify-center mt-10">
          <div className="w-12 h-12 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin"></div>
        </div>
      )}

      {review && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="mt-16 space-y-12"
        >
          {/* Score */}
          <div className="flex flex-col items-center gap-6">
            <ScoreGauge score={review.score} />

            <button
              onClick={exportPDF}
              className="bg-indigo-600 hover:bg-indigo-300 px-6 py-3 rounded-xl transition cursor-pointer"
            >
              Export PDF
            </button>
          </div>

          {/* Issues */}
          {Object.keys(grouped).map((category) => (
            <div key={category}>
              <h2 className="text-2xl text-center font-semibold mb-6 capitalize border-b border-white/10 pb-4">
                {category}
              </h2>

              {grouped[category].map((issue, i) => (
                <IssueCard key={i} issue={issue} />
              ))}
            </div>
          ))}

          {/* Suggestions */}
          <div>
            <h2 className="text-2xl font-semibold mb-6">Top Improvements</h2>

            <div className="grid md:grid-cols-2 gap-6">
              {review.suggestions?.map((s, i) => (
                <div
                  key={i}
                  className="bg-slate-800 border border-white/10 rounded-xl p-6 transition hover:scale-105"
                >
                  <h4 className="text-red-400 font-semibold mb-2">Before</h4>
                  <p className="text-sm">{s.before}</p>

                  <h4 className="text-green-400 font-semibold mt-4 mb-2">
                    After
                  </h4>
                  <p className="text-sm">{s.after}</p>
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      )}
    </div>
  );
}

function ScoreGauge({ score }) {
  const radius = 70;
  const stroke = 12;
  const normalizedRadius = radius - stroke * 2;
  const circumference = normalizedRadius * 2 * Math.PI;
  const strokeDashoffset = circumference - (score / 100) * circumference;

  return (
    <div className="relative w-48 h-48 left-7">
      <svg height={radius * 2} width={radius * 2}>
        <circle
          stroke="rgba(255,255,255,0.1)"
          fill="transparent"
          strokeWidth={stroke}
          r={normalizedRadius}
          cx={radius}
          cy={radius}
        />
        <motion.circle
          stroke="#6366f1"
          fill="transparent"
          strokeWidth={stroke}
          strokeDasharray={circumference}
          strokeDashoffset={circumference}
          animate={{ strokeDashoffset }}
          transition={{ duration: 1 }}
          r={normalizedRadius}
          cx={radius}
          cy={radius}
        />
      </svg>
      <div
        className={`absolute inset-0 top-13 ${
          score > 9 ? "left-13" : "left-15"
        } text-3xl font-bold`}
      >
        {score}
      </div>
    </div>
  );
}

function IssueCard({ issue }) {
  const [open, setOpen] = useState(false);

  return (
    <motion.div
      layout
      onClick={() => setOpen(!open)}
      className="cursor-pointer bg-slate-800 border border-white/10 rounded-xl p-5 mb-4 hover:bg-slate-700 transition"
    >
      <h3 className="font-bold text-lg">{issue.title}</h3>

      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="mt-3 text-sm text-gray-300"
        >
          <p>{issue.reason}</p>
          <p className="mt-2 text-indigo-400">Proof: {issue.proof}</p>
        </motion.div>
      )}
    </motion.div>
  );
}

export default Home;
